language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
dist: trusty
env:
  global:
  - EXTRA_DEPS="inotify"
  - DEPOPTS="github"
  - PINS="inotify"
  matrix:
  - OCAML_VERSION=4.02
  - OCAML_VERSION=4.03
os:
  - linux
