language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  - DEPOPTS=github
    PINS="github hvsock:https://github.com/djs55/ocaml-hvsock.git"
os:
  - linux
  - osx
