platform:
  - x86

environment:
  CYG_ROOT: "C:\\cygwin"
  CYG_BASH: "%CYG_ROOT%\\bin\\bash -lc"
  TESTS: "false"
  OPAM_SWITCH: "4.03.0+mingw64c"
  PINS: "datakit-server:. git.1.9.3:https://github.com/mirage/ocaml-git.git#1.9.3 named-pipe.0.4.0:https://github.com/mirage/ocaml-named-pipe.git#0.4.0 protocol-9p.0.7.4:https://github.com/mirage/ocaml-9p.git#v0.7.4"

install:
  - appveyor DownloadFile https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/appveyor-opam.sh
  - "%CYG_ROOT%\\setup-x86.exe -qnNdO -R %CYG_ROOT% -s http://cygwin.mirror.constant.com -l C:/cygwin/var/cache/setup -P rsync -P patch -P diffutils -P make -P unzip -P git -P m4 -P perl -P mingw64-x86_64-gcc-core"

build_script:
  - "%CYG_BASH% '${APPVEYOR_BUILD_FOLDER}/appveyor-opam.sh'"
  - "%CYG_BASH% -c 'cd ${APPVEYOR_BUILD_FOLDER}; make exe COMMIT'"
  - cmd: copy %APPVEYOR_BUILD_FOLDER%\Datakit\datakit.exe c:\projects\datakit\com.docker.db.exe
  - cmd: copy %APPVEYOR_BUILD_FOLDER%\Datakit\zlib1.dll c:\projects\datakit\zlib1.dll

artifacts:
  - path: "com.docker.db.exe"
  - path: "zlib1.dll"
  - path: "COMMIT"
